### ISSUE TITLE
Add box shadow on hover for Screenshots

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-web#60]
It would be great to include a box shadow effect when hovering over screenshots to indicate clickable content.

**Comment by kernc** [comment]
Adding
```css
#features div.screenshot-container div.content:hover
{
    background: #fea;
}
```
would look quite alright if thumbnails had transparent background.
